db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD

getter:
  restart: always
  image: iic2113grupo1/news-getter
  ports:
    - '5000:5000'

web:
  restart: always
  image: iic2113grupo1/tuconstituyes
  command: rails server -b 0.0.0.0
  ports:
    - '80:3000'
  links:
    - db
  environment:
    - SECRET_KEY_BASE

newrelic:
  image: uzyexe/newrelic
  restart: "on-failure"
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/dev:/dev"
    - "/sys:/sys"
  environment:
    - NEW_RELIC_LICENSE_KEY
  pid: host
  net: host
